version: "1.0"
info:
  model: int-scaffold
packages:
- name: SiqaBugBashTestProject
  gitServerName: siqagituserforbugbash
  gitUrl: https://github.com/siqagituser/SiqaBugBashTestProject
  gitUsername: siqagituser
  gitBranch: main
- name: SIQA_OriginTest_OnPremAssets
  gitServerName: SIQA_Origin
  gitUrl: https://github.com/vijetadixit
  gitUsername: vijetadixit
  gitBranch: Test
services:
- serviceName: project.siqabugbashtest.integrations:FS1
  packages:
  - name: SiqaBugBashTestProject
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.0.0.0.890
- serviceName: project.siqabugbashtest.integrations:FS2
  packages:
  - name: SiqaBugBashTestProject
    version: "1.0"
